FROM node:12-alpine

WORKDIR /main

COPY ./package.json /main

RUN npm install

COPY ./public /main/public
COPY ./src /main/src
COPY ./server/frontend.js /main/server/frontend.js

RUN npm run build

EXPOSE 3000

CMD ["node", "server/frontend.js"]